title:              My Portfolio
email:              rira9817@gmail.com
description:        Project/Study
author:             EunJee Jo
baseurl:            ""
url:                "https://eunjee.github.io"

# Social Profiles
twitter_username:   
github_username:    eunjee
facebook_username:  
linkedin_username:

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
